### ISSUE TITLE
When using -s getting "UnhandledPromiseRejectionWarning: TypeError: invalid options argument"

### ISSUE THREAD

**Issue by kshep** [arjunmehta/node-sqldump-to-json#53]
node v14.17.6

Trying to use -s I get:

```
(node:18939) UnhandledPromiseRejectionWarning: TypeError: invalid options argument
    at optsArg (/usr/local/lib/node_modules/sqldump-to/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/usr/local/lib/node_modules/sqldump-to/node_modules/mkdirp/index.js:11:10)
    at /usr/local/lib/node_modules/sqldump-to/lib/util/fs.js:24:5
    at new Promise (<anonymous>)
    at writeToFileDir (/usr/local/lib/node_modules/sqldump-to/lib/util/fs.js:23:10)
    at SQLConverterStream.writeSchema (/usr/local/lib/node_modules/sqldump-to/lib/sql-converter-stream.js:308:5)
    at SQLConverterStream.runReadSchema (/usr/local/lib/node_modules/sqldump-to/lib/sql-converter-stream.js:283:16)
    at SQLConverterStream.determineState (/usr/local/lib/node_modules/sqldump-to/lib/sql-converter-stream.js:148:14)
    at SQLConverterStream.handleNewBuffer (/usr/local/lib/node_modules/sqldump-to/lib/sql-converter-stream.js:124:14)
    at SQLConverterStream._write (/usr/local/lib/node_modules/sqldump-to/lib/sql-converter-stream.js:106:10)
```

**Comment by arjunmehta** [comment]
@kshep Sorry for the delay on this. This seems to have to do with the version of mkdirp sqldump-to is using. This bug was introduced with #43

Fixing this now and will release a patch shortly.

**Comment by arjunmehta** [comment]
Fixed in this [PR](https://github.com/arjunmehta/sqldump-to/pull/54)
